default: &default
  adapter: postgresql
  encoding: unicode
  database: grafakeql_development
  pool: 5
  username: grafakeql
  password: password

development:
  <<: *default
  database: grafakeql_development

test:
  <<: *default
  database: grafakeql_test

production:
  <<: *default
  database: grafakeql_production
