default: &default
  adapter: mysql2
  encoding: utf8
  database: grafakeql_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: grafakeql_development

test:
  <<: *default
  database: grafakeql_test

production:
  <<: *default
  database: grafakeql_production
